const RIDES_NOT_FOUND_ERROR = 'RIDES_NOT_FOUND_ERROR';
const VALIDATION_ERROR = 'VALIDATION_ERROR';
const SERVER_ERROR = 'SERVER_ERROR';

module.exports = {RIDES_NOT_FOUND_ERROR, VALIDATION_ERROR, SERVER_ERROR};
